version: '3.8'

services:
  soranow:
    image: teraccc/soranew:latest
    container_name: soranow
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
    restart: unless-stopped
